[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[images]
  remote_images = ['https://.*\.supabase\.co/storage/.*']

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
