/**
 * cartes.ts — La table des cartes connues du moteur.
 *
 * v0.2 : import complet des 120 premières cartes Blue Rising (set BR1, n° 1→120),
 * depuis l'export bluedex (cards_rows). Les stats (cout/puissance/soutien),
 * types, factions et sous-types viennent directement de la base.
 *
 * - `effet` = identifiant d'effet ; sa logique vit dans blueRising.ts. Seules les
 *   cartes déjà implémentées par le moteur ont un identifiant ; les autres sont à
 *   `null` (le moteur les traite comme sans effet tant qu'on ne les code pas).
 * - `texte` = texte de jeu brut (référence, non utilisé par le moteur ; accents
 *   simplifiés à l'import).
 * - `motsCles` = mots-clés détectés dans le texte ("rage", "resistant",
 *   "distance", "contreattaque", "furtif").
 */
export const CARTES = {
    1: { id: 1, nom: "Arthur", type: "personnage", sousType: "heros", faction: "emissaire", cout: 2, puissance: 4, soutien: 1, effet: null, motsCles: [], texte: "Avant : Puissance +1." },
    2: { id: 2, nom: "Recrue de l'Étoile Bleue", type: "personnage", sousType: "aspirant", faction: "emissaire", cout: 1, puissance: 1, soutien: 1, effet: "tap_ressource1", motsCles: [], texte: "rotation Gagnez 1 Ressource." },
    3: { id: 3, nom: "Reapered & Zeph", type: "personnage", sousType: "heros", faction: "gardien", cout: 2, puissance: 3, soutien: 2, effet: null, motsCles: [], texte: "Aucun." },
    4: { id: 4, nom: "Bibi", type: "personnage", sousType: "heros", faction: "emissaire", cout: 3, puissance: 5, soutien: 1, effet: null, motsCles: [], texte: "rotation Echange son emplacement avec un autre personnage allie." },
    5: { id: 5, nom: "Gardien néophyte", type: "personnage", sousType: "aspirant", faction: "gardien", cout: 1, puissance: 1, soutien: 1, effet: "attaque_plus2", motsCles: [], texte: "Attaque +2." },
    6: { id: 6, nom: "Émissaire néophyte", type: "personnage", sousType: "aspirant", faction: "emissaire", cout: 1, puissance: 1, soutien: 1, effet: null, motsCles: [], texte: "Arriere : Puissance +1." },
    7: { id: 7, nom: "Veilleur néophyte", type: "personnage", sousType: "aspirant", faction: "veilleur", cout: 1, puissance: 1, soutien: 1, effet: null, motsCles: ["distance"], texte: "Attaque a distance." },
    8: { id: 8, nom: "Le Blue Wall", type: "personnage", sousType: "heros", faction: "veilleur", cout: 2, puissance: 3, soutien: 2, effet: "etb_jeton1", motsCles: [], texte: "En arrivant en jeu creez un jeton Ecuyer." },
    9: { id: 9, nom: "Safiaa", type: "personnage", sousType: "heros", faction: "veilleur", cout: 4, puissance: 5, soutien: 2, effet: null, motsCles: [], texte: "Defense +2." },
    10: { id: 10, nom: "Fatih", type: "personnage", sousType: "aspirant", faction: "veilleur", cout: 1, puissance: 1, soutien: 1, effet: null, motsCles: [], texte: "Defense +2." },
    11: { id: 11, nom: "Wao", type: "personnage", sousType: "heros", faction: "gardien", cout: 3, puissance: 6, soutien: 1, effet: null, motsCles: [], texte: "Aucun." },
    12: { id: 12, nom: "Augustin, le conteur", type: "personnage", sousType: "heros", faction: "emissaire", cout: 4, puissance: 6, soutien: 2, effet: null, motsCles: [], texte: "rotation Echange son emplacement avec un autre personnage allie." },
    13: { id: 13, nom: "Ripp", type: "personnage", sousType: "aspirant", faction: "gardien", cout: 1, puissance: 1, soutien: 2, effet: null, motsCles: [], texte: "Aucun." },
    14: { id: 14, nom: "Inoxtag", type: "personnage", sousType: "heros", faction: "gardien", cout: 4, puissance: 5, soutien: 2, effet: null, motsCles: ["contreattaque"], texte: "Contre-Attaque." },
    15: { id: 15, nom: "Tabard de l'an 25", type: "objet", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne rotation A la fin du tour, redressez le personnage equipe. EMISSAIRE: Cout -1." },
    16: { id: 16, nom: "Les trompettes de la victoire", type: "objet", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne Defense +2." },
    17: { id: 17, nom: "Couronne du prince", type: "objet", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: ["resistant"], texte: "Le personnage equipe gagne Resistant." },
    18: { id: 18, nom: "Bons Souvenirs", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne rotation Piocher 1 carte. VEILLEUR: Cout -1." },
    19: { id: 19, nom: "Chiens de combats", type: "objet", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne Puissance +1." },
    20: { id: 20, nom: "Bootcamp", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Chaque joueur choisit un de ses personnages et le renvoie en main." },
    21: { id: 21, nom: "Chouette mecanique", type: "piege", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: "piege_chouette", motsCles: [], texte: "Le defenseur gagne Puissance +2. VEILLEUR : Puissance +2." },
    22: { id: 22, nom: "Les premiers pas", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez un piege." },
    23: { id: 23, nom: "Fausse alerte", type: "piege", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: "piege_faussealerte", motsCles: [], texte: "L'attaque prend fin immediatement. Renvoyez le defenseur en main si c'est un personnage." },
    24: { id: 24, nom: "Rugissement des Ultras", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: "ev_rugissement", motsCles: [], texte: "Un personnage gagne Puissance +2. GARDIEN: Puissance +1." },
    25: { id: 25, nom: "Piege de glace", type: "piege", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: "piege_glace", motsCles: [], texte: "Le defenseur gagne Puissance +4." },
    26: { id: 26, nom: "Adversaires", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "ev_adversaires", motsCles: [], texte: "Un personnage gagne Puissance +4. GARDIEN: Puissance +2." },
    27: { id: 27, nom: "Campagne de printemps", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: "ev_campagne", motsCles: [], texte: "Renvoyez en main un de vos personnages pour piocher 2 cartes. Piochez 3 cartes s'il s'agit d'un jeton Ecuyer." },
    28: { id: 28, nom: "Campagne d'été", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Un personnage gagne Puissance +1. S'il attaque, le defenseur ne peut pas recevoir de soutien. GARDIEN: Puissance +1." },
    29: { id: 29, nom: "Les Voix", type: "piege", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le defenseur gagne Puissance +3. A la fin du combat, si le defenseur est un personnage, renvoyez-le en main." },
    30: { id: 30, nom: "Appel des renforts", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: ["furtif"], texte: "Un personnage gagne puissance +2 et Furtif. Emissaire : Cout -1." },
    31: { id: 31, nom: "Défense inébranlable", type: "evenement", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Renvoyez en main un Heros." },
    32: { id: 32, nom: "Double Victoire", type: "evenement", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Renvoyez en main un personnage present sur la ligne Arriere." },
    33: { id: 33, nom: "Reverse Sweep", type: "piege", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "L'attaque prend fin immediatement." },
    34: { id: 34, nom: "Étude des artefacts", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Renvoyer en main 1 personnage depuis votre defausse." },
    35: { id: 35, nom: "Marché de reliques", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez 1 objet." },
    36: { id: 36, nom: "Kameto", type: "personnage", sousType: "legende", faction: "emissaire", cout: 5, puissance: 8, soutien: 2, effet: null, motsCles: ["resistant"], texte: "Resistant. Les objets joues sur vos personnages coutent 0 Ressource." },
    37: { id: 37, nom: "Busio", type: "personnage", sousType: "heros", faction: "gardien", cout: 2, puissance: 3, soutien: 2, effet: null, motsCles: ["rage"], texte: "Rage." },
    38: { id: 38, nom: "Canna", type: "personnage", sousType: "legende", faction: "gardien", cout: 5, puissance: 8, soutien: 1, effet: "reste_si_tue_heros", motsCles: ["resistant"], texte: "Resistant, N'est pas renvoye en main lorsqu'il detruit un Heros." },
    39: { id: 39, nom: "Atow", type: "personnage", sousType: "heros", faction: "emissaire", cout: 2, puissance: 4, soutien: 1, effet: null, motsCles: ["furtif"], texte: "Furtif (n'active pas les pieges en attaque)." },
    40: { id: 40, nom: "Yukino", type: "personnage", sousType: "aspirant", faction: "gardien", cout: 1, puissance: 1, soutien: 1, effet: null, motsCles: ["contreattaque"], texte: "Contre-Attaque." },
    41: { id: 41, nom: "Suygetsu", type: "personnage", sousType: "heros", faction: "veilleur", cout: 2, puissance: 3, soutien: 1, effet: "tap_pioche1", motsCles: [], texte: "rotation Piochez 1 carte. Utilisable uniquement pendant son tour." },
    42: { id: 42, nom: "Glance", type: "personnage", sousType: "legende", faction: "veilleur", cout: 5, puissance: 8, soutien: 2, effet: null, motsCles: ["resistant", "distance"], texte: "Resistant. Attaque a distance." },
    43: { id: 43, nom: "Jiex", type: "personnage", sousType: "heros", faction: "veilleur", cout: 4, puissance: 4, soutien: 1, effet: null, motsCles: [], texte: "rotation Piochez 2 cartes. Utilisable uniquement pendant son tour." },
    44: { id: 44, nom: "Anesilia", type: "personnage", sousType: "heros", faction: "veilleur", cout: 3, puissance: 4, soutien: 2, effet: null, motsCles: ["distance"], texte: "Attaque a distance." },
    45: { id: 45, nom: "Domingo", type: "personnage", sousType: "heros", faction: "gardien", cout: 3, puissance: 4, soutien: 2, effet: "attaque_plus3", motsCles: [], texte: "Attaque +3." },
    46: { id: 46, nom: "Jiraya", type: "personnage", sousType: "heros", faction: "emissaire", cout: 3, puissance: 4, soutien: 2, effet: null, motsCles: [], texte: "Les objets joues sur Jiraya coutent 0 Ressources." },
    47: { id: 47, nom: "Kenny", type: "personnage", sousType: "aspirant", faction: "emissaire", cout: 1, puissance: 1, soutien: 1, effet: null, motsCles: [], texte: "rotation Echange son emplacement avec un autre personnage allie." },
    48: { id: 48, nom: "Tweekz", type: "personnage", sousType: "heros", faction: "gardien", cout: 4, puissance: 6, soutien: 1, effet: null, motsCles: [], texte: "N'est pas renvoye en main lorsqu'il reussit une attaque contre l'Environnement." },
    49: { id: 49, nom: "Étoiles", type: "personnage", sousType: "heros", faction: "emissaire", cout: 4, puissance: 5, soutien: 2, effet: null, motsCles: [], texte: "Se redresse a la fin de son tour." },
    50: { id: 50, nom: "Kitty", type: "personnage", sousType: "aspirant", faction: "veilleur", cout: 1, puissance: 1, soutien: 1, effet: "etb_pioche1", motsCles: [], texte: "En arrivant en jeu, piochez une carte." },
    51: { id: 51, nom: "Peluche Popo", type: "objet", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez cet objet : redressez le personnage equipe." },
    52: { id: 52, nom: "Tabard de l'an 21", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe ne peut pas etre renvoye en main par l'effet d'une carte adverse." },
    53: { id: 53, nom: "Épée du matin", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne Attaque +2. GARDIEN: Cout -1." },
    54: { id: 54, nom: "Bannière bleue", type: "objet", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez cet objet : le personnage equipe gagne Puissance +1." },
    55: { id: 55, nom: "Char à propulsion", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Lors de votre tour, le personnage peut se deplacer sur un emplacement libre." },
    56: { id: 56, nom: "Carte stratégique", type: "objet", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne rotation Gagnez 1 Ressource. EMISSAIRE: gagnez +1 Ressource." },
    57: { id: 57, nom: "KCX", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Vous pouvez changer l'emplacement de tous vos personnage." },
    58: { id: 58, nom: "KCX II", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez un personnage Aspirant ou jeton Ecuyer." },
    59: { id: 59, nom: "Fumigène", type: "piege", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "piege_fumigene", motsCles: [], texte: "Creez jusqu'a 2 Ecuyers sur des emplacements libres. Inclinez un Veilleur pour creer jusqu'a 2 Ecuyers de plus." },
    60: { id: 60, nom: "Communiqué de la Karmine", type: "piege", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "piege_communique", motsCles: [], texte: "Redressez tous vos personnages." },
    61: { id: 61, nom: "Le split oublié", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: "ev_split", motsCles: [], texte: "Tout vos Ecuyers gagnent +2 en Puissance et +2 en Soutien." },
    62: { id: 62, nom: "Contrat Karmine", type: "evenement", sousType: null, faction: null, cout: 4, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Chaque joueur renvoie en main tous ses personnages, sauf un." },
    63: { id: 63, nom: "Vilains gobelins", type: "piege", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Changez l'emplacement d'un de vos personnages. EMISSAIRE: redressez le personnage." },
    64: { id: 64, nom: "Campagne d'hiver", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Gagnez 2 Ressources." },
    65: { id: 65, nom: "L'artefact volé", type: "piege", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "L'attaque prend fin immediatement. Renvoyez l'attaquant en main." },
    66: { id: 66, nom: "Blue vs Red", type: "piege", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Jouez un personnage dans la colonne (en payant son cout)." },
    67: { id: 67, nom: "Nouvelles du jour", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Regardez un piege. Vous pouvez le deplacer sur un emplacement libre." },
    68: { id: 68, nom: "Signature Caliste", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: ["rage"], texte: "Un personnage gagne Rage. GARDIEN : Puissance +1" },
    69: { id: 69, nom: "Archives du Pays Bleu", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: "ev_archives", motsCles: ["distance"], texte: "Un personnage gagne Attaque a distance (attaque un personnage au lieu d'une colonne). Veilleur : Puissance +1" },
    70: { id: 70, nom: "La catastrophe", type: "piege", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: "piege_pioche3", motsCles: [], texte: "Piochez 3 cartes." },
    71: { id: 71, nom: "Banter", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "L'attaquant attaque la colonne de votre choix." },
    72: { id: 72, nom: "Ville de Sirap", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 3, soutien: 0, effet: "env_ressources_veilleur", motsCles: [], texte: "rotation Gagnez 2 Ressources utilisables uniquement pour jouer des personnages Veilleur." },
    73: { id: 73, nom: "Ville de Nilreb", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 3, soutien: 0, effet: "env_ressources_gardien", motsCles: [], texte: "Gagnez 2 Ressources utilisables uniquement pour jouer des personnages Gardien." },
    74: { id: 74, nom: "Champs de Bataille", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 3, soutien: 0, effet: null, motsCles: [], texte: "rotation Gagnez 2 Ressources emissaire." },
    75: { id: 75, nom: "Cristal d'Azur", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Reussir une attaque contre l'Environnement adverse > Remettez toutes les cartes de votre defausse dans votre deck." },
    76: { id: 76, nom: "Arche de l'étoile", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Avoir 3 objets en jeu > Renvoyez en main jusqu'a 3 objets venant de votre defausse." },
    77: { id: 77, nom: "Colonnes des Champions", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Votre adversaire elimine une de vos Legendes > Jouez un Heros depuis votre main sans payer son cout." },
    78: { id: 78, nom: "Disque d'or des Sables Grondants", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: "art_disque", motsCles: [], texte: "Gagner 2 Points de Victoire ou plus lors du meme tour > Redressez tous vos personnages a la fin de votre tour." },
    79: { id: 79, nom: "Replique du Renouveau", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Commencer votre tour avec moins de 2 cartes en main > Piochez 3 cartes." },
    80: { id: 80, nom: "Orbe des Reines Bleues", type: "artefact", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: "art_orbe", motsCles: [], texte: "Avoir moins de 2 personnages en jeu > Creez jusqu'a 6 Ecuyers." },
    81: { id: 81, nom: "Ferra", type: "personnage", sousType: "heros", faction: "emissaire", cout: 2, puissance: 3, soutien: 1, effet: null, motsCles: [], texte: "Retour Gagnez 2 ressources" },
    82: { id: 82, nom: "Smartseven", type: "personnage", sousType: "heros", faction: "veilleur", cout: 2, puissance: 3, soutien: 1, effet: null, motsCles: ["distance"], texte: "Un personnage Veilleur gagne Attaque a distance." },
    83: { id: 83, nom: "Kotei", type: "personnage", sousType: "heros", faction: "emissaire", cout: 2, puissance: 3, soutien: 1, effet: null, motsCles: [], texte: "rotation Redresse un personnage Emissaire." },
    84: { id: 84, nom: "Blidzy", type: "personnage", sousType: "heros", faction: "gardien", cout: 2, puissance: 4, soutien: 1, effet: "attaque_plus2", motsCles: [], texte: "Attaque +2." },
    85: { id: 85, nom: "Ze1sh", type: "personnage", sousType: "heros", faction: "veilleur", cout: 2, puissance: 4, soutien: 1, effet: null, motsCles: [], texte: "Deplacez un piege sur un emplacement libre." },
    86: { id: 86, nom: "Caliste", type: "personnage", sousType: "legende", faction: "gardien", cout: 5, puissance: 8, soutien: 1, effet: null, motsCles: ["rage", "resistant"], texte: "Resistant. Rage." },
    87: { id: 87, nom: "Kyeahoo", type: "personnage", sousType: "heros", faction: "gardien", cout: 2, puissance: 3, soutien: 1, effet: null, motsCles: ["rage"], texte: "rotation Un personnage Gardien gagne Rage." },
    88: { id: 88, nom: "Yike", type: "personnage", sousType: "heros", faction: "gardien", cout: 3, puissance: 5, soutien: 0, effet: null, motsCles: ["contreattaque"], texte: "Contre-Attaque." },
    89: { id: 89, nom: "Vatira", type: "personnage", sousType: "legende", faction: "emissaire", cout: 5, puissance: 8, soutien: 2, effet: null, motsCles: ["resistant", "furtif"], texte: "Resistant. Furtif." },
    90: { id: 90, nom: "Juicy", type: "personnage", sousType: "heros", faction: "emissaire", cout: 3, puissance: 3, soutien: 2, effet: null, motsCles: [], texte: "Se redresse a la fin de son tour." },
    91: { id: 91, nom: "Avez", type: "personnage", sousType: "heros", faction: "veilleur", cout: 4, puissance: 5, soutien: 3, effet: "aura_veilleur_def1", motsCles: [], texte: "Tous vos autres personnages Veilleur gagnent Defense +1." },
    92: { id: 92, nom: "N4rrate", type: "personnage", sousType: "legende", faction: "veilleur", cout: 5, puissance: 7, soutien: 2, effet: null, motsCles: ["resistant"], texte: "Resistant. Defense +3." },
    93: { id: 93, nom: "Alkyia", type: "personnage", sousType: "heros", faction: "veilleur", cout: 3, puissance: 4, soutien: 2, effet: "etb_jeton2", motsCles: [], texte: "En arrivant en jeu, creez 2 jetons Ecuyer." },
    94: { id: 94, nom: "Nisqy", type: "personnage", sousType: "heros", faction: "gardien", cout: 4, puissance: 5, soutien: 2, effet: "aura_gardien_att1", motsCles: [], texte: "Tous vos autres personnages Gardien gagnent Attaque +1." },
    95: { id: 95, nom: "Zack Nani", type: "personnage", sousType: "heros", faction: "emissaire", cout: 4, puissance: 5, soutien: 2, effet: null, motsCles: [], texte: "Tous vos autres personnages Emissaire gagnent Soutien +1." },
    96: { id: 96, nom: "Bracelet de l'amitié", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe n'est pas renvoye en main lorsqu'il detruit un Heros." },
    97: { id: 97, nom: "Tabard de l'an 23", type: "objet", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez cet objet: gagnez 1 Ressource." },
    98: { id: 98, nom: "Tabard de l'an 24", type: "objet", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez cet objet : le personnage equipe gagne Soutien +1." },
    99: { id: 99, nom: "Perticoins", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne rotation Gagnez 2 Ressources. Emissaire : gagnez +1 Ressource." },
    100: { id: 100, nom: "Le chapeau d'Atow", type: "objet", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Le personnage equipe gagne Soutien +2." },
    101: { id: 101, nom: "Fusil à Lunette", type: "objet", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: ["distance"], texte: "Le personnage equipe gagne Attaque a distance. Veilleur: Cout -1." },
    102: { id: 102, nom: "Lunettes de vitesse", type: "objet", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Detruisez cet objet : renvoyez en main le personnage equipe." },
    103: { id: 103, nom: "KCX III", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Jouez un objet sur un de vos personnages en payant 1 ressource de moins." },
    104: { id: 104, nom: "KCX IV", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Renvoyez en main tous vos personnages, puis jouez 1 personnage sans payer son cout." },
    105: { id: 105, nom: "Triomphe", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "ev_triomphe", motsCles: [], texte: "Si le personnage detruit un Heros, annulez son renvoi en main. Gardien : Cout -1." },
    106: { id: 106, nom: "Dernier Espoir", type: "evenement", sousType: null, faction: null, cout: 8, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Renvoyer en main tous les personnages en jeu. Cout -1 par emplacement de personnage libre." },
    107: { id: 107, nom: "Sourire d'enfer", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Regardez tous les pieges et detruisez-en un." },
    108: { id: 108, nom: "Vague bleue", type: "piege", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Changez l'emplacement de tout ou partie de vos personnages." },
    109: { id: 109, nom: "Défaillance d'énergie", type: "piege", sousType: null, faction: null, cout: 3, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Tous vos personnages gagnent Puissance +3." },
    110: { id: 110, nom: "Annonce spéciale", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Redressez un personnage. Emissaire : Cout -1." },
    111: { id: 111, nom: "Extraction d'énergie", type: "evenement", sousType: null, faction: null, cout: 1, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Piochez 1 carte par point de victoire de l'adversaire." },
    112: { id: 112, nom: "KC was not interested", type: "piege", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "piege_kc", motsCles: [], texte: "Renvoyez en main l'attaquant et le defenseur si c'est un personnage. Veilleur: ne renvoyez pas en main le defenseur." },
    113: { id: 113, nom: "Soutien invétéré", type: "piege", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: null, motsCles: ["contreattaque"], texte: "Le defenseur gagne Puissance +1 en Contre-Attaque. Gardien : Puissance +1" },
    114: { id: 114, nom: "Caca (Canna x Caliste)", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Un personnage allie gagne Puissance +2, defaussez-le a la fin du combat. VEILLEUR: A la place, renvoyez-le en main." },
    115: { id: 115, nom: "Mercato", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Regardez la main de l'adversaire et defaussez 1 carte non-personnage." },
    116: { id: 116, nom: "Cri de guerre", type: "evenement", sousType: null, faction: null, cout: 2, puissance: 0, soutien: 0, effet: "ev_cri", motsCles: [], texte: "Inclinez un de vos personnages pour ajouter sa puissance a celle d'un autre personnage." },
    117: { id: 117, nom: "Conseils spéciaux", type: "evenement", sousType: null, faction: null, cout: 0, puissance: 0, soutien: 0, effet: null, motsCles: [], texte: "Deplacez un personnage adverse sur un emplacement libre et inclinez-le." },
    118: { id: 118, nom: "Les Arenes", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 5, soutien: 0, effet: null, motsCles: [], texte: null },
    119: { id: 119, nom: "L'Académie de l'Étoile Bleue", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 3, soutien: 0, effet: null, motsCles: [], texte: "rotation Piochez 1 carte." },
    120: { id: 120, nom: "Trix City", type: "environnement", sousType: null, faction: null, cout: 0, puissance: 2, soutien: 0, effet: null, motsCles: [], texte: "rotation Soutien +1. Peut soutenir n'importe quel personnage. Ne compte pas dans la limite de soutien." },
};
export const JETON_ECUYER = -1; // id spécial : jeton Écuyer 1/0, retiré du jeu s'il meurt
/** Les deux decks de test (42 cartes chacun, listes v2 validées). */
export const DECK_ECUYER = [
    ...rep(93, 3), ...rep(91, 2), ...rep(42, 1), ...rep(50, 3), ...rep(8, 3),
    ...rep(2, 2), ...rep(13, 2), ...rep(41, 2), ...rep(7, 2),
    ...rep(69, 2), ...rep(27, 3), ...rep(61, 2),
    ...rep(21, 2), ...rep(23, 2), ...rep(59, 3), ...rep(70, 3), ...rep(112, 3),
];
export const ENV_ECUYER = 72, ART_ECUYER = 80;
export const DECK_GARDIEN = [
    ...rep(84, 3), ...rep(38, 1), ...rep(86, 2), ...rep(45, 2), ...rep(5, 3),
    ...rep(50, 2), ...rep(94, 2), ...rep(2, 2), ...rep(13, 2), ...rep(11, 3), ...rep(88, 2),
    ...rep(26, 2), ...rep(116, 2), ...rep(24, 2), ...rep(105, 3),
    ...rep(60, 2), ...rep(70, 3), ...rep(25, 2),
];
export const ENV_GARDIEN = 73, ART_GARDIEN = 78;
function rep(id, n) { return Array(n).fill(id); }
